"use client";

import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { HydrationGate } from "@/components/ui/hydration-gate";
import { Icon } from "@/components/ui/icon";
import { useDemo } from "@/features/demo/demo-provider";
import { moduleFourLessons } from "@/features/learning/module-four-content";
import { getPathwayStatus } from "@/features/learning/pathway";

export default function ModuleFourPage() {
  const { state } = useDemo();
  const status = getPathwayStatus(state);
  const next = moduleFourLessons.find((lesson) => !state.moduleFourCompletedLessonIds.includes(lesson.id));
  return <HydrationGate><AppShell active="learn" contentClassName="learning-reading-scale">
    <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/dashboard">My learning</Link><Icon name="chevron-right" /><span>Module 4</span></nav>
    <header className="module-hero source-module-hero"><div><span className="module-badge">Module 4 · Your lesson material</span><h1>Make resources<br /><em>from your material.</em></h1><p>Use lesson notes you have permission to share. Make a worksheet, quiz, or slide outline, then check the facts and adapt the draft for your class.</p><div className="metadata-row"><span><Icon name="book" />8 lessons</span><span><Icon name="target" />Guided practice + a saved resource</span><span><Icon name="clock" />260 minutes</span></div><Link className="button button-primary" href={next ? `/learn/module-4/lessons/${next.id}` : "/learn/module-4/studio"}>{next ? "Continue lessons" : "Open your portfolio"}<Icon name="arrow-right" /></Link></div><aside className="source-evidence-note" aria-label="Example of source verification"><span className="eyebrow">A quick example</span><p className="source-sample-claim">“Water must boil before it evaporates.”</p><div><span className="source-label">A:2</span><p>Evaporation can happen below the boiling point.</p></div><strong><Icon name="x" /> The notes say something different.</strong><p>Check the notes, correct the sentence, and explain what you changed.</p></aside></header>
    <section className="learning-outcomes" aria-labelledby="source-outcomes-title"><div className="outcomes-icon"><Icon name="target" /></div><div><h2 id="source-outcomes-title">By the end, you can</h2><ul><li><Icon name="check" />Select permitted, relevant sources without private learner information.</li><li><Icon name="check" />Ask AI to use your notes and show where its facts come from.</li><li><Icon name="check" />Check facts against your notes and notice when information is missing.</li><li><Icon name="check" />Edit a resource to suit your class without changing the facts.</li><li><Icon name="check" />Save your reviewed resource with credit and notes on your changes.</li></ul></div></section>
    <section className="source-studio-callout" aria-labelledby="studio-callout-title"><div><span className="eyebrow">Try it step by step</span><h2 id="studio-callout-title">Source Studio</h2><p>Try a short science or reading example. Check three statements against the notes, prepare a draft, and review it before classroom use.</p><ul><li>No external account required</li><li>Guided practice with honest feedback</li><li>Download your requests and practice notes</li></ul></div><div><span className={`status-pill ${status.sourceReady ? "passed" : "available"}`}>{status.sourceReady ? "Portfolio evidence recorded" : "Ready to explore"}</span><Link className="button button-primary" href="/learn/module-4/studio">Try guided resource practice <Icon name="arrow-right" /></Link></div></section>
    <section className="staffroom-callout"><div><span className="eyebrow">Use your own permitted material</span><h2>Bring a short teaching resource.</h2><p>Paste or upload non-sensitive text, choose a classroom format, then review and export the draft.</p></div><Link className="button button-secondary" href="/learn/module-4/transform">Use my lesson material<Icon name="arrow-right" /></Link></section>
    <section className="activity-section" aria-labelledby="source-pathway-title"><div className="section-heading"><div><span className="eyebrow">The learning route</span><h2 id="source-pathway-title">Eight lessons. One resource you’ve checked.</h2></div><span className="section-meta">{status.fourLessons}/{moduleFourLessons.length} lessons complete</span></div><ol className="activity-list">{moduleFourLessons.map((lesson, index) => {
      const done = state.moduleFourCompletedLessonIds.includes(lesson.id);
      return <li className={done ? "completed" : ""} key={lesson.id}><span className="activity-order">{done ? <Icon name="check" /> : index + 1}</span><div className="activity-copy"><span>{done ? "Completed" : "Explore any time"} · {lesson.durationMinutes} min</span><h3>{lesson.title}</h3><p>{lesson.summary}</p></div><Link className="button button-secondary button-small" href={`/learn/module-4/lessons/${lesson.id}`}>{done ? "Review" : "Start"}<Icon name="arrow-right" /></Link></li>;
    })}</ol></section>
    <section className="staffroom-callout"><div><span className="eyebrow">Applied knowledge check</span><h2>Check what you’ve learned.</h2><p>Five classroom decisions about sources, citations, conflicts, access and safe handoff. Four correct answers pass, with explanations and unlimited retries. Module completion also requires all eight lessons and a complete Source Studio portfolio.</p></div><Link className="button button-primary" href="/learn/module-4/quiz">{status.fourPassed ? "Review knowledge check" : "Take knowledge check"}<Icon name="arrow-right" /></Link></section>
    {status.fourPassed ? <section className="privacy-card wide"><Icon name="check" /><div><strong>Module 4 complete.</strong><p>{status.courseComplete ? "All four course modules and their required evidence are complete. Your learning record is available in Progress." : "Your source portfolio and assessment evidence are recorded. Other modules retain their own completion requirements."}</p><Link className="text-link" href="/progress">View course progress <Icon name="arrow-right" /></Link></div></section> : null}
    <p className="source-helper">The guided Studio uses original practice material. An approved Google notebook is optional. A portfolio export records practice evidence and does not issue a certificate.</p>
  </AppShell></HydrationGate>;
}
