"use client";

import type { Route } from "next";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { getLearningPlan } from "@/components/learning-plan";
import { RequirementList } from "@/components/requirement-list";
import { HydrationGate } from "@/components/ui/hydration-gate";
import { Icon } from "@/components/ui/icon";
import { ProgressRing } from "@/components/ui/progress-ring";
import { useDemo } from "@/features/demo/demo-provider";
import { getPathwayStatus } from "@/features/learning/pathway";

export default function DashboardPage() {
  const { state } = useDemo();
  const modules = getLearningPlan(state);
  const status = getPathwayStatus(state);
  const next = modules.find((module) => !module.passed);
  const completedLessons = modules.reduce((count, module) => count + module.completed, 0);
  const recent = modules.flatMap((module) => module.attempts.map((attempt) => ({ ...attempt, module }))).sort((a, b) => b.attemptedAt.localeCompare(a.attemptedAt)).slice(0, 3);
  return <HydrationGate><AppShell active="home">
    <header className="page-heading dashboard-heading"><div><span className="eyebrow">Your practice book</span><h1>Welcome{state.displayName ? `, ${state.displayName}` : " back"}.</h1><p>A little practice today. Something useful for your next lesson.</p></div><span className="dashboard-tally"><strong>{completedLessons}</strong> of 29 lessons complete</span></header>
    {!state.onboardingCompleted ? <section className="empty-state-card"><span className="empty-state-icon"><Icon name="user" /></span><div><span className="eyebrow">Before you begin</span><h2>Set up your learning space</h2><p>Review safe-use habits and add your teaching context. It takes about three minutes.</p></div><Link className="button button-primary" href="/onboarding/safe-use">Finish setup<Icon name="arrow-right" /></Link></section> : null}
    <section className="continue-card" aria-labelledby="continue-title"><div className="continue-card-main"><span className="eyebrow">{next ? `Your next step · Module ${next.position}` : "Your course record"}</span><h2 id="continue-title">{next ? next.title : "Your four-module practice record is complete."}</h2><p>{next ? next.next.label : "You have completed every lesson, knowledge check and required practice record."}</p><Link className="button button-primary" href={(next?.next.href ?? "/progress") as Route}>{next ? "Continue learning" : "View completion record"}<Icon name="arrow-right" /></Link><span className="continue-note">You can explore every module in any order.</span></div><div className="continue-progress"><ProgressRing value={status.coursePercent} /><strong>{status.completedModules} of 4 modules complete</strong><span>Lessons + required evidence</span></div></section>
    <div className="dashboard-grid"><section className="dashboard-main-column" aria-labelledby="modules-title"><div className="section-heading"><div><span className="eyebrow">Four useful habits</span><h2 id="modules-title">Your learning route</h2></div><Link className="text-link" href="/progress">View full record<Icon name="arrow-right" /></Link></div><div className="learning-route">{modules.map((module) => <article className={`route-row${module.passed ? " route-complete" : ""}`} key={module.id}><span className="route-number">{module.passed ? <Icon name="check" /> : String(module.position).padStart(2, "0")}</span><div className="route-copy"><div className="route-meta"><span>{module.estimatedMinutes} min · {module.lessons.length} lessons</span><span>{module.passed ? "Complete" : module.completed ? "In progress" : "Ready to explore"}</span></div><h3><Link href={`/learn/${module.slug}` as Route}>{module.title}</Link></h3><p>{module.description}</p><div className="route-progress"><div className="linear-progress" role="progressbar" aria-label={`${module.title} completion`} aria-valuenow={module.percent} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${module.percent}%` }} /></div><span>{module.completed}/{module.lessons.length} lessons</span></div></div><Link className="route-action" href={`/learn/${module.slug}` as Route} aria-label={`Open Module ${module.position}: ${module.title}`}><Icon name="arrow-right" /></Link></article>)}</div></section>
    <aside className="dashboard-aside">{next ? <section className="next-requirements"><span className="eyebrow">To complete Module {next.position}</span><h2>What remains</h2><RequirementList requirements={next.requirements} incompleteOnly /></section> : <section className="next-requirements"><Icon name="check" /><h2>All requirements recorded</h2><p>Your progress page brings your results and practice evidence together.</p><Link className="text-link" href="/progress">Open progress<Icon name="arrow-right" /></Link></section>}<section className="privacy-card"><Icon name="shield" /><div><strong>Make the example fictional.</strong><p>Keep names, marks and learner records out of your practice.</p></div></section><section className="activity-card"><div className="section-heading compact"><h2>Recent checks</h2></div>{recent.length ? <ul>{recent.map((attempt, index) => <li key={`${attempt.attemptedAt}-${index}`}><span className="activity-icon"><Icon name={attempt.passed ? "check" : "refresh"} /></span><div><strong>Module {attempt.module.position} · {attempt.scorePercent}%</strong><small>{attempt.passed ? "Knowledge check passed" : "Ready to review and retry"}</small></div></li>)}</ul> : <div className="mini-empty"><Icon name="book" /><p>Your submitted knowledge checks will appear here. Start with any module.</p></div>}</section></aside></div>
  </AppShell></HydrationGate>;
}
