"use client";

import type { Route } from "next";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { getLearningPlan } from "@/components/learning-plan";
import { RequirementList } from "@/components/requirement-list";
import { HydrationGate } from "@/components/ui/hydration-gate";
import { Icon } from "@/components/ui/icon";
import { ProgressRing } from "@/components/ui/progress-ring";
import { useDemo } from "@/features/demo/demo-provider";
import { getPathwayStatus } from "@/features/learning/pathway";

export default function DashboardPage() {
  const { state } = useDemo();
  const modules = getLearningPlan(state);
  const status = getPathwayStatus(state);
  const next = modules.find((module) => !module.passed);
  const nextLesson = next?.lessons.find((lesson) => next.next.href.endsWith(`/lessons/${lesson.id}`));
  const completedLessons = modules.reduce((count, module) => count + module.completed, 0);
  const recent = modules.flatMap((module) => module.attempts.map((attempt) => ({ ...attempt, module }))).sort((a, b) => b.attemptedAt.localeCompare(a.attemptedAt)).slice(0, 3);
  return <HydrationGate><AppShell active="home">
    <header className="page-heading dashboard-heading"><div><span className="eyebrow">Your learning, at a glance</span><h1>Hello{state.displayName ? `, ${state.displayName}` : " there"}.</h1><p>What would you like to try for your next lesson?</p></div><span className="dashboard-tally"><strong>{completedLessons}</strong> of 29 lessons complete</span></header>
    {!state.onboardingCompleted ? <section className="empty-state-card"><span className="empty-state-icon"><Icon name="user" /></span><div><span className="eyebrow">Before you begin</span><h2>Set up your learning space</h2><p>Tell us about your teaching and any AI tools you’ve tried. We’ll help you get started.</p></div><Link className="button button-primary" href="/onboarding/safe-use">Finish setup<Icon name="arrow-right" /></Link></section> : null}
    <section className="continue-card" aria-labelledby="continue-title"><div className="continue-card-main"><span className="eyebrow">{next ? `Start here · Module ${next.position}` : "Your course record"}</span><h2 id="continue-title">{next ? next.title : "You’ve completed all four modules."}</h2><p>{next ? (nextLesson ? `Next lesson: ${nextLesson.title}` : next.next.label) : "Your lessons, quizzes, and teaching practice are complete. You can return to any activity."}</p><Link className="button button-primary" href={(next?.next.href ?? "/progress") as Route}>{next ? "Continue learning" : "See my progress"}<Icon name="arrow-right" /></Link><span className="continue-note">New to AI? Start here. You can explore any module whenever you like.</span></div><div className="continue-progress"><ProgressRing value={status.coursePercent} /><strong>{status.completedModules} of 4 modules complete</strong><span>Lessons, practice, and quick checks</span></div></section>
    <div className="dashboard-grid"><section className="dashboard-main-column" aria-labelledby="modules-title"><div className="section-heading"><div><span className="eyebrow">Four useful habits</span><h2 id="modules-title">Choose what to learn</h2></div><Link className="text-link" href="/progress">My progress<Icon name="arrow-right" /></Link></div><div className="learning-route">{modules.map((module) => <article className={`route-row${module.passed ? " route-complete" : ""}`} key={module.id}><span className="route-number">{module.passed ? <Icon name="check" /> : String(module.position).padStart(2, "0")}</span><div className="route-copy"><div className="route-meta"><span>{module.estimatedMinutes} min · {module.lessons.length} lessons</span><span>{module.passed ? "Complete" : module.completed ? "In progress" : "Ready to explore"}</span></div><h3><Link href={`/learn/${module.slug}` as Route}>{module.title}</Link></h3><p>{module.description}</p><div className="route-progress"><div className="linear-progress" role="progressbar" aria-label={`${module.title} completion`} aria-valuenow={module.percent} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${module.percent}%` }} /></div><span>{module.completed}/{module.lessons.length} lessons</span></div></div><Link className="route-action" href={`/learn/${module.slug}` as Route} aria-label={`Open Module ${module.position}: ${module.title}`}><Icon name="arrow-right" /></Link></article>)}</div></section>
    <aside className="dashboard-aside">{next ? <section className="next-requirements"><span className="eyebrow">To complete Module {next.position}</span><h2>Finish this module</h2><p>Learn the ideas, try them, and take a quick check. Your progress is saved as you go.</p><details><summary>See what’s left to do</summary><RequirementList requirements={next.requirements} incompleteOnly /></details></section> : <section className="next-requirements"><Icon name="check" /><h2>All requirements recorded</h2><p>Your progress page brings your results and practice evidence together.</p><Link className="text-link" href="/progress">Open progress<Icon name="arrow-right" /></Link></section>}<section className="privacy-card"><Icon name="shield" /><div><strong>Keep student details private.</strong><p>Practise with made-up examples. Leave out names, marks, and student records.</p></div></section><section className="activity-card"><div className="section-heading compact"><h2>Recent checks</h2></div>{recent.length ? <ul>{recent.map((attempt, index) => <li key={`${attempt.attemptedAt}-${index}`}><span className="activity-icon"><Icon name={attempt.passed ? "check" : "refresh"} /></span><div><strong>Module {attempt.module.position} · {attempt.scorePercent}%</strong><small>{attempt.passed ? "Knowledge check passed" : "Ready to review and retry"}</small></div></li>)}</ul> : <div className="mini-empty"><Icon name="book" /><p>Your quiz results will appear here. There’s no time limit—learn at your own pace.</p></div>}</section></aside></div>
  </AppShell></HydrationGate>;
}
